# Base image
FROM php:8.1-apache

# Install dependencies and extensions
RUN apt-get update && apt-get install -y \
    && docker-php-ext-install -j$(nproc) mysqli pdo_mysql

# Install Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
RUN mkdir /var/www/api/
COPY ./apache-config-backend/000-default.conf /etc/apache2/sites-available/000-default.conf
COPY ./apache-config-backend/ports.conf /etc/apache2/ports.conf
#WORKDIR /usr/local/etc/php

# Set working directory
WORKDIR /var/www/api/
#COPY ../backend/composer.json /var/www/api/
# Copy files and install dependencies

#RUN composer install --no-dev --optimize-autoloader

# Enable Apache modules
RUN a2enmod rewrite

EXPOSE 8080

CMD ["apachectl", "-D", "FOREGROUND"]