FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Rome

RUN apt-get update && apt-get install -y \
php apache2 python3 python3-pip

RUN a2enmod rewrite

COPY ./apache-config-frontend/000-default.conf /etc/apache2/sites-available/000-default.conf
COPY ./apache-config-frontend/ports.conf /etc/apache2/ports.conf
EXPOSE 80

CMD ["apache2ctl", "-D", "FOREGROUND"]